apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: default
data:
  index.html: |
    <html>
    <head>
    <title>*** TEST NGINX 1.19 ***</title>
    </head>
    <body>
    <h1>*** TEST NGINX 1.19 ***</h1>
    </br>
    <h1>TEST ConfigMap Netology Kuber 3.4</h1>
    </body>
    </html
