---
all:
  hosts:
    sonar-01:
      ansible_host: 158.160.4.62
    nexus-01:
      ansible_host: 158.160.17.120
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/home/ubuntu/.ssh/id_rsa"
