resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    [master]
    master-1.ru-central1.internal ansible_host=${yandex_compute_instance.master[0].network_interface.0.nat_ip_address}

    [nodes]
    node-1.ru-central1.internal ansible_host=${yandex_compute_instance.node[0].network_interface.0.nat_ip_address}
    node-2.ru-central1.internal ansible_host=${yandex_compute_instance.node[1].network_interface.0.nat_ip_address}
    node-3.ru-central1.internal ansible_host=${yandex_compute_instance.node[2].network_interface.0.nat_ip_address}
    DOC
  filename = "./ansible/inventory.ini"

  depends_on = [
    yandex_compute_instance.master,
    yandex_compute_instance.node
  ]
}
