resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [master]
    master ansible_host=${yandex_compute_instance.master.network_interface.0.nat_ip_address}
 
    [nodes]
    node1 ansible_host=${yandex_compute_instance.node1.network_interface.0.nat_ip_address}
    node2 ansible_host=${yandex_compute_instance.node2.network_interface.0.nat_ip_address}
    node3 ansible_host=${yandex_compute_instance.node3.network_interface.0.nat_ip_address}

    [jenkinsmaster]
    jenkins-master-01.ru-central1.internal ansible_host=${yandex_compute_instance.jenkins-master01.network_interface.0.nat_ip_address}
  
    [jenkinsagent]
    jenkins-agent-01.ru-central1.internal ansible_host=${yandex_compute_instance.jenkins-agent01.network_interface.0.nat_ip_address}

    DOC
  filename = "./ansible/inventory.ini"

  depends_on = [
    yandex_compute_instance.master,
    yandex_compute_instance.node1,
    yandex_compute_instance.node2,
    yandex_compute_instance.node3,
    yandex_compute_instance.jenkins-master01,
    yandex_compute_instance.jenkins-agent01
  ]
}
